const BASE_KANA = [
  { row: 'vowel', romaji: 'a', hiragana: 'あ', katakana: 'ア' },
  { row: 'vowel', romaji: 'i', hiragana: 'い', katakana: 'イ' },
  { row: 'vowel', romaji: 'u', hiragana: 'う', katakana: 'ウ' },
  { row: 'vowel', romaji: 'e', hiragana: 'え', katakana: 'エ' },
  { row: 'vowel', romaji: 'o', hiragana: 'お', katakana: 'オ' },
  { row: 'k', romaji: 'ka', hiragana: 'か', katakana: 'カ' },
  { row: 'k', romaji: 'ki', hiragana: 'き', katakana: 'キ' },
  { row: 'k', romaji: 'ku', hiragana: 'く', katakana: 'ク' },
  { row: 'k', romaji: 'ke', hiragana: 'け', katakana: 'ケ' },
  { row: 'k', romaji: 'ko', hiragana: 'こ', katakana: 'コ' },
  { row: 's', romaji: 'sa', hiragana: 'さ', katakana: 'サ' },
  { row: 's', romaji: 'shi', hiragana: 'し', katakana: 'シ' },
  { row: 's', romaji: 'su', hiragana: 'す', katakana: 'ス' },
  { row: 's', romaji: 'se', hiragana: 'せ', katakana: 'セ' },
  { row: 's', romaji: 'so', hiragana: 'そ', katakana: 'ソ' },
  { row: 't', romaji: 'ta', hiragana: 'た', katakana: 'タ' },
  { row: 't', romaji: 'chi', hiragana: 'ち', katakana: 'チ' },
  { row: 't', romaji: 'tsu', hiragana: 'つ', katakana: 'ツ' },
  { row: 't', romaji: 'te', hiragana: 'て', katakana: 'テ' },
  { row: 't', romaji: 'to', hiragana: 'と', katakana: 'ト' },
  { row: 'n', romaji: 'na', hiragana: 'な', katakana: 'ナ' },
  { row: 'n', romaji: 'ni', hiragana: 'に', katakana: 'ニ' },
  { row: 'n', romaji: 'nu', hiragana: 'ぬ', katakana: 'ヌ' },
  { row: 'n', romaji: 'ne', hiragana: 'ね', katakana: 'ネ' },
  { row: 'n', romaji: 'no', hiragana: 'の', katakana: 'ノ' },
  { row: 'h', romaji: 'ha', hiragana: 'は', katakana: 'ハ' },
  { row: 'h', romaji: 'hi', hiragana: 'ひ', katakana: 'ヒ' },
  { row: 'h', romaji: 'fu', hiragana: 'ふ', katakana: 'フ' },
  { row: 'h', romaji: 'he', hiragana: 'へ', katakana: 'ヘ' },
  { row: 'h', romaji: 'ho', hiragana: 'ほ', katakana: 'ホ' },
  { row: 'm', romaji: 'ma', hiragana: 'ま', katakana: 'マ' },
  { row: 'm', romaji: 'mi', hiragana: 'み', katakana: 'ミ' },
  { row: 'm', romaji: 'mu', hiragana: 'む', katakana: 'ム' },
  { row: 'm', romaji: 'me', hiragana: 'め', katakana: 'メ' },
  { row: 'm', romaji: 'mo', hiragana: 'も', katakana: 'モ' },
  { row: 'y', romaji: 'ya', hiragana: 'や', katakana: 'ヤ' },
  { row: 'y', romaji: 'yu', hiragana: 'ゆ', katakana: 'ユ' },
  { row: 'y', romaji: 'yo', hiragana: 'よ', katakana: 'ヨ' },
  { row: 'r', romaji: 'ra', hiragana: 'ら', katakana: 'ラ' },
  { row: 'r', romaji: 'ri', hiragana: 'り', katakana: 'リ' },
  { row: 'r', romaji: 'ru', hiragana: 'る', katakana: 'ル' },
  { row: 'r', romaji: 're', hiragana: 'れ', katakana: 'レ' },
  { row: 'r', romaji: 'ro', hiragana: 'ろ', katakana: 'ロ' },
  { row: 'w', romaji: 'wa', hiragana: 'わ', katakana: 'ワ' },
  { row: 'w', romaji: 'wo', hiragana: 'を', katakana: 'ヲ' },
  { row: 'n', romaji: 'n', hiragana: 'ん', katakana: 'ン' },
];

const DAKUTEN_KANA = [
  { row: 'k', romaji: 'ga', hiragana: 'が', katakana: 'ガ' },
  { row: 'k', romaji: 'gi', hiragana: 'ぎ', katakana: 'ギ' },
  { row: 'k', romaji: 'gu', hiragana: 'ぐ', katakana: 'グ' },
  { row: 'k', romaji: 'ge', hiragana: 'げ', katakana: 'ゲ' },
  { row: 'k', romaji: 'go', hiragana: 'ご', katakana: 'ゴ' },
  { row: 's', romaji: 'za', hiragana: 'ざ', katakana: 'ザ' },
  { row: 's', romaji: 'ji', hiragana: 'じ', katakana: 'ジ' },
  { row: 's', romaji: 'zu', hiragana: 'ず', katakana: 'ズ' },
  { row: 's', romaji: 'ze', hiragana: 'ぜ', katakana: 'ゼ' },
  { row: 's', romaji: 'zo', hiragana: 'ぞ', katakana: 'ゾ' },
  { row: 't', romaji: 'da', hiragana: 'だ', katakana: 'ダ' },
  { row: 't', romaji: 'ji', hiragana: 'ぢ', katakana: 'ヂ' },
  { row: 't', romaji: 'zu', hiragana: 'づ', katakana: 'ヅ' },
  { row: 't', romaji: 'de', hiragana: 'で', katakana: 'デ' },
  { row: 't', romaji: 'do', hiragana: 'ど', katakana: 'ド' },
  { row: 'h', romaji: 'ba', hiragana: 'ば', katakana: 'バ' },
  { row: 'h', romaji: 'bi', hiragana: 'び', katakana: 'ビ' },
  { row: 'h', romaji: 'bu', hiragana: 'ぶ', katakana: 'ブ' },
  { row: 'h', romaji: 'be', hiragana: 'べ', katakana: 'ベ' },
  { row: 'h', romaji: 'bo', hiragana: 'ぼ', katakana: 'ボ' },
];

const HANDAKUTEN_KANA = [
  { row: 'h', romaji: 'pa', hiragana: 'ぱ', katakana: 'パ' },
  { row: 'h', romaji: 'pi', hiragana: 'ぴ', katakana: 'ピ' },
  { row: 'h', romaji: 'pu', hiragana: 'ぷ', katakana: 'プ' },
  { row: 'h', romaji: 'pe', hiragana: 'ぺ', katakana: 'ペ' },
  { row: 'h', romaji: 'po', hiragana: 'ぽ', katakana: 'ポ' },
];

const COMBINATION_KANA = [
  { row: 'k', romaji: 'kya', hiragana: 'きゃ', katakana: 'キャ' },
  { row: 'k', romaji: 'kyu', hiragana: 'きゅ', katakana: 'キュ' },
  { row: 'k', romaji: 'kyo', hiragana: 'きょ', katakana: 'キョ' },
  { row: 'k', romaji: 'gya', hiragana: 'ぎゃ', katakana: 'ギャ' },
  { row: 'k', romaji: 'gyu', hiragana: 'ぎゅ', katakana: 'ギュ' },
  { row: 'k', romaji: 'gyo', hiragana: 'ぎょ', katakana: 'ギョ' },
  { row: 's', romaji: 'sha', hiragana: 'しゃ', katakana: 'シャ' },
  { row: 's', romaji: 'shu', hiragana: 'しゅ', katakana: 'シュ' },
  { row: 's', romaji: 'sho', hiragana: 'しょ', katakana: 'ショ' },
  { row: 't', romaji: 'cha', hiragana: 'ちゃ', katakana: 'チャ' },
  { row: 't', romaji: 'chu', hiragana: 'ちゅ', katakana: 'チュ' },
  { row: 't', romaji: 'cho', hiragana: 'ちょ', katakana: 'チョ' },
  { row: 'n', romaji: 'nya', hiragana: 'にゃ', katakana: 'ニャ' },
  { row: 'n', romaji: 'nyu', hiragana: 'にゅ', katakana: 'ニュ' },
  { row: 'n', romaji: 'nyo', hiragana: 'にょ', katakana: 'ニョ' },
  { row: 'h', romaji: 'hya', hiragana: 'ひゃ', katakana: 'ヒャ' },
  { row: 'h', romaji: 'hyu', hiragana: 'ひゅ', katakana: 'ヒュ' },
  { row: 'h', romaji: 'hyo', hiragana: 'ひょ', katakana: 'ヒョ' },
  { row: 'h', romaji: 'bya', hiragana: 'びゃ', katakana: 'ビャ' },
  { row: 'h', romaji: 'byu', hiragana: 'びゅ', katakana: 'ビュ' },
  { row: 'h', romaji: 'byo', hiragana: 'びょ', katakana: 'ビョ' },
  { row: 'h', romaji: 'pya', hiragana: 'ぴゃ', katakana: 'ピャ' },
  { row: 'h', romaji: 'pyu', hiragana: 'ぴゅ', katakana: 'ピュ' },
  { row: 'h', romaji: 'pyo', hiragana: 'ぴょ', katakana: 'ピョ' },
];

function toKanaRecords(entries, group) {
  return entries.flatMap(({ row, romaji, hiragana, katakana }) => [
    {
      id: `${romaji}-hiragana`,
      script: 'hiragana',
      glyph: hiragana,
      romaji,
      row,
      group,
    },
    {
      id: `${romaji}-katakana`,
      script: 'katakana',
      glyph: katakana,
      romaji,
      row,
      group,
    },
  ]);
}

export const KANA_DATA = [
  ...toKanaRecords(BASE_KANA, 'base'),
  ...toKanaRecords(DAKUTEN_KANA, 'dakuten'),
  ...toKanaRecords(HANDAKUTEN_KANA, 'handakuten'),
  ...toKanaRecords(COMBINATION_KANA, 'combination'),
];
